<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="CD059" name="tc_BasicDispatch_SelectPrinter_SampleAcknowledgementByTechnician_DDCRefundCancel.S54_Canceling2of4ServicesWithItemLevelDiscountInAmountAndPatientFullyPaidTheBill" tests="1" failures="1" timestamp="11 Jun 2018 07:33:20 GMT" time="23.480" errors="0">
  <testcase name="s54_Canceling2of4ServicesWithItemLevelDiscountInAmountAndPatientFullyPaidTheBill" time="23.480" classname="tc_BasicDispatch_SelectPrinter_SampleAcknowledgementByTechnician_DDCRefundCancel.S54_Canceling2of4ServicesWithItemLevelDiscountInAmountAndPatientFullyPaidTheBill">
    <failure type="java.lang.AssertionError" message="***Registration --&gt; Alert msg not displayed as expected.*** expected [Saved successfully] but found [Something went wrong]">
      <![CDATA[java.lang.AssertionError: ***Registration --> Alert msg not displayed as expected.*** expected [Saved successfully] but found [Something went wrong]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at tc_BasicDispatch_SelectPrinter_SampleAcknowledgementByTechnician_DDCRefundCancel.S54_Canceling2of4ServicesWithItemLevelDiscountInAmountAndPatientFullyPaidTheBill.s54_Canceling2of4ServicesWithItemLevelDiscountInAmountAndPatientFullyPaidTheBill(S54_Canceling2of4ServicesWithItemLevelDiscountInAmountAndPatientFullyPaidTheBill.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- s54_Canceling2of4ServicesWithItemLevelDiscountInAmountAndPatientFullyPaidTheBill -->
</testsuite> <!-- tc_BasicDispatch_SelectPrinter_SampleAcknowledgementByTechnician_DDCRefundCancel.S54_Canceling2of4ServicesWithItemLevelDiscountInAmountAndPatientFullyPaidTheBill -->
